nodeLinker: node-modules
enableGlobalCache: true
networkConcurrency: 8
npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  '@next/eslint-plugin-next@*':
    peerDependencies:
      eslint: '*'
